services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php74
    ports:
    - "9000:9000"  
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: polaris2022
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Developerd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./docker/mssql:/var/opt/mssql/scripts
    command: /bin/bash -c "(/opt/mssql/bin/sqlservr &) && sleep 30 && if [ -d /var/opt/mssql/scripts ]; then for f in /var/opt/mssql/scripts/*.sql; do /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '@Developerd' -i $$f; done; fi && while true; do sleep 3600; done"
volumes:  
  mssql-data: